# These are supported funding model platforms

# Support Codev Project Development
# github: [VinodHatti7019]  # Uncomment when GitHub Sponsors is enabled

# Buy me a coffee to support continued development
# buy_me_a_coffee: codevproject

# Custom sponsorship - Support open source development
custom: ['https://github.com/VinodHatti7019/Codev/blob/main/CONTRIBUTING.md', 'https://github.com/VinodHatti7019/Codev/issues']
